name: Build on Nightly

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 21
          distribution: zulu
      - run: |
          # download the latest nightly Flix JAR
          url="https://github.com/mlutze/flix-nightly/releases/latest/download/flix.jar"
          curl -L -f "$url" > flix.jar

          # run tests
          java -jar flix.jar test --github-token ${{ github.token }}
