name: Build on Latest Release

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 17
          distribution: zulu
      - run: |
          # download Flix JAR
          curl -L https://github.com/flix/flix/releases/latest/download/flix.jar > flix.jar

          # install dependencies
          java -jar flix.jar install JonathanStarup/Flix-ANSI-Terminal
          java -jar flix.jar install mlutze/flix-json

          # run tests
          java -jar flix.jar test
